name: Run tests before accept pull request 

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install node v14.19.0
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.19.0'

      - name: Install package.json dependencies
        run: |
          npm i

      - name: Run tests
        run: |
          npm run test:integration
          npm run test:unit